import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Investigator } from "@/components/prom/Investigator";
import { KnowledgeGraph } from "@/components/prom/KnowledgeGraph";
import { Eyebrow, Mono, Tag } from "@/components/prom/Panel";
import { TxInspector } from "@/components/prom/TxInspector";

export const Route = createFileRoute("/evidence")({
  head: () => ({
    meta: [
      { title: "Evidence Room — PROMETHEUS Fraud Twin" },
      {
        name: "description",
        content:
          "Forensic case file investigation, claim-to-evidence resolution, multi-agent accountability logs, and graph fracture tracing.",
      },
    ],
  }),
  component: EvidencePage,
});

function EvidencePage() {
  const [fractureTraj, setFractureTraj] = useState<string | null>(null);
  const [playFracture, setPlayFracture] = useState<number>(0);

  const triggerFracture = (trajId: string | null) => {
    setFractureTraj(trajId);
    setPlayFracture(Date.now());
  };

  return (
    <div className="space-y-8 pb-16">
      {/* Editorial Header */}
      <section className="border-b border-white/14 bg-black/75 backdrop-blur-md px-4 sm:px-6 py-6 sm:py-10">
        <div className="mx-auto max-w-[1400px]">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <Eyebrow className="text-defense font-semibold">FORENSIC INTELLIGENCE // EVIDENCE ROOM</Eyebrow>
            <div className="flex items-center gap-2">
              <Tag tone="defense">VERIFIABLE CLAIMS</Tag>
              <Tag tone="muted">AGENT ACCOUNTABILITY</Tag>
            </div>
          </div>
          <h1 className="mt-3 font-display text-3xl sm:text-5xl text-white leading-tight">
            Formal case files & evidence-linked narratives.
          </h1>
          <p className="mt-3 max-w-2xl text-xs sm:text-sm text-white/85 leading-relaxed font-normal">
            Every analytical claim resolves to an explicit evidence artifact generated by a named
            specialist agent. If an agent fails to contribute or exceeds its budget, the shortfall is
            audited openly.
          </p>
        </div>
      </section>

      {/* Main Evidence Workspace */}
      <div className="mx-auto max-w-[1400px] px-4 sm:px-6 space-y-8 sm:space-y-10">
        {/* The Investigator Case File */}
        <section>
          <div className="mb-3 flex items-baseline justify-between">
            <Eyebrow>Active Forensic Case File</Eyebrow>
            <Mono className="text-muted-foreground">interactive claim → evidence binding</Mono>
          </div>
          <Investigator />
        </section>

        {/* Trajectory Graph & Fracture Animation */}
        <section>
          <div className="mb-3 flex items-baseline justify-between">
            <Eyebrow>Trajectory Subgraph & Fracture</Eyebrow>
            <Mono className="text-muted-foreground">sequential hop-by-hop tracing</Mono>
          </div>
          <KnowledgeGraph
            fractureTrajectory={fractureTraj}
            onTrajectoryChange={triggerFracture}
            playFracture={playFracture}
          />
        </section>

        {/* Individual Transaction Inspector */}
        <section>
          <div className="mb-3 flex items-baseline justify-between">
            <Eyebrow>Transaction Signal Inspector</Eyebrow>
            <Mono className="text-muted-foreground">atomic risk & counterfactual drill-down</Mono>
          </div>
          <TxInspector />
        </section>
      </div>
    </div>
  );
}
