/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttackRouteImport } from './routes/attack'
import { Route as DefenseRouteImport } from './routes/defense'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ProtocolRouteImport } from './routes/protocol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackRoute = AttackRouteImport.update({
  id: '/attack',
  path: '/attack',
  getParentRoute: () => rootRouteImport,
} as any)
const DefenseRoute = DefenseRouteImport.update({
  id: '/defense',
  path: '/defense',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attack': typeof AttackRoute
  '/defense': typeof DefenseRoute
  '/evidence': typeof EvidenceRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attack': typeof AttackRoute
  '/defense': typeof DefenseRoute
  '/evidence': typeof EvidenceRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attack': typeof AttackRoute
  '/defense': typeof DefenseRoute
  '/evidence': typeof EvidenceRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attack' | '/defense' | '/evidence' | '/protocol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attack' | '/defense' | '/evidence' | '/protocol'
  id: '__root__' | '/' | '/attack' | '/defense' | '/evidence' | '/protocol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttackRoute: typeof AttackRoute
  DefenseRoute: typeof DefenseRoute
  EvidenceRoute: typeof EvidenceRoute
  ProtocolRoute: typeof ProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack': {
      id: '/attack'
      path: '/attack'
      fullPath: '/attack'
      preLoaderRoute: typeof AttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defense': {
      id: '/defense'
      path: '/defense'
      fullPath: '/defense'
      preLoaderRoute: typeof DefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttackRoute: AttackRoute,
  DefenseRoute: DefenseRoute,
  EvidenceRoute: EvidenceRoute,
  ProtocolRoute: ProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
